<div class="dis_policies_mainwrapper privacy_mainpolicy">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
			<div class="dis_policies_wrapper privacy_policy">
				<div class="dis_policies_sidebar">
					<div class="policies_content">
						<div class="policies_content_box">
							<div class="au_heading">
								<h2>Terms Of Use</h2>
							</div>
							<h4 class="policies_heading sub_heading">Effective Date: September 15, 2019</h4>
							
							<p>Welcome to Discovered! It is our pleasure to provide the services described below for your personal enjoyment and entertainment in accordance with these Terms of Use ("Terms"). Please take a moment to carefully read through these Terms.</p>
							<p>As a preliminary matter, we wanted to highlight a topic that you will read more about later. At Discovered, we expect that our world-class customer service team, which can be contacted through our Help Center at <a href="https://discovered.tv" class="policies_link" target="_blank">Discovered.tv/help</a>, will be able to resolve any issues you may have as you enjoy our services. In the unlikely event that an issue between us remains unresolved, please note that THESE TERMS REQUIRE ARBITRATION ON AN INDIVIDUAL BASIS, RATHER THAN JURY TRIALS OR CLASS ACTIONS. ALSO, THESE TERMS SET FORTH SPECIFIC REMEDIES AVAILABLE TO YOU. PLEASE SEE SECTIONS 12 AND 14 TO LEARN MORE.</p>
							
							<h4 class="policies_heading" id="01">01. DESCRIPTION OF SERVICE AND ACCEPTANCE OF TERMS</h4>
							<p>Discovered USA Inc., ("Discovered," "we," or "us") provides an online video service which gives users the opportunity to select from various offerings of live and on-demand programming, including television shows, movies, clips, and other content (collectively, the "Content"). Our video service, the Content, our player for viewing the Content (the "Video Player") and any other products, features, tools, materials, or other services (including third party branded services) offered from time to time by Discovered through a variety of Access Points (defined below) are referred to collectively as the "Services." The term "Access Points" refers to, collectively, the <a href="https://discovered.tv" class="policies_link" target="_blank">Discovered.tv/help</a> website (the "Discovered Site"), applications, and other places where any Services are available, including websites and applications of Discovered’s third party distribution partners and other websites where users or website operators are permitted to embed or have otherwise licensed the Video Player.</p>
							<p>Use of the Services (including access to the Content) is subject to compliance with these Terms which incorporate by reference our Privacy Policy available at <a href="https://discovered.tv" class="policies_link" target="_blank">Discovered.tv/privacy</a> ("Privacy Policy") and any end user license agreement that might accompany the applicable Service. Therefore, by accessing or using any of the Services through any Access Point (including by visiting the Discovered Site or by downloading or launching the Discovered application), you accept and agree to these Terms.</p>
							<p>Please note that the website addresses (i.e., URLs) included within these Terms may not function as hyperlinks on all the Access Points. To view these Terms with clickable hyperlinks, please visit the Discovered Site on your computer.</p>
							
							<h4 class="policies_heading" id="02">02. CHANGES TO THESE TERMS</h4>
							<p>We may need to make changes to these Terms from time to time for many reasons. For example, we may need to reflect updates in how the Services work or changes in the law. You should look at these Terms regularly, which are posted on the Discovered site at <a href="https://discovered.tv" class="policies_link" target="_blank">Discovered.tv/terms</a>. In addition, you can access these Terms from Discovered applications. If we make a material change to these Terms, we will notify you by posting a notice on the Discovered site. If you are a registered user, we will also send an email to the email address you most recently provided to us prior to the material change taking effect. Therefore, it is important that you keep your account information, including email address, updated. Any material change to these Terms will be effective automatically 30 days after the revised Terms are first posted or, for users who register or otherwise provide opt-in consent during this 30-day period, at the time of registration or consent, as applicable.</p>
							
							<h4 class="policies_heading" id="03">03. ACCESS AND USE OF THE SERVICES</h4>
							<p>3.1 Age Limitations. The Services are not intended to be used by children without involvement and approval of a parent or guardian. If you are under the age of 13, you are not permitted to register with Discovered or provide your personal information to Discovered. If you are at least 13 and under 18 years of age (or under the applicable age of majority in your state or territory of residence), you may register with Discovered only if you have the consent of your parent or guardian, including consent to these Terms on your behalf, and for clarity, may only modify an account, or associated profiles, with the consent of your parent or guardian.</p>
							<p>3.2 Your License. Discovered is pleased to grant you a non-exclusive limited license to use the Services, including accessing and viewing the Content on a streaming-only basis through the Video Player, for personal, non-commercial purposes as set forth in these Terms. The periods during which you can view each piece of Content will vary based on the rights availability of such Content and the terms of your subscription.</p>
							<p>3.3 Profiles. Discovered offers the option to personalize use of the Services through the creation of one or more profiles under one account. Only the account holder, and those with permission from the account holder, may create a profile.</p>
							<p>3.4 The Content.</p>
							<p>a. Usage Rules and Limitations. You may only access and view the Content personally and for a non-commercial purpose in compliance with these Terms. You may not either directly or through the use of any device, software, internet site, web-based service, or other means remove, alter, bypass, avoid, interfere with, or circumvent any copyright, trademark, or other proprietary notices marked on the Content or any digital rights management mechanism, device, or other content protection or access control measure associated with the Content including geo-filtering mechanisms. You may not either directly or through the use of any device, software, internet site, web-based service, or other means copy, record, download, stream capture, reproduce, duplicate, archive, distribute, upload, publish, modify, translate, broadcast, perform, display, sell, or transmit or retransmit the Content unless expressly permitted by the terms of your subscription or otherwise by Discovered in writing. You may not incorporate the Content into, or stream or retransmit the Content via, any hardware or software application or make it available via frames or in-line links unless expressly permitted by Discovered in writing. Furthermore, you may not create, recreate, distribute or advertise an index of any significant portion of the Content unless authorized by Discovered. You may not build a business utilizing the Content, whether or not for profit. The Content covered by these restrictions includes without limitation any text, graphics, layout, interface, logos, photographs, audio and video materials, and stills. In addition, you are strictly prohibited from creating derivative works or materials that otherwise are derived from or based on in any way the Content, including montages, mash-ups and similar videos, wallpaper, desktop themes, greeting cards, and merchandise, unless expressly permitted by Discovered in writing. This prohibition applies even if you intend to give away the derivative materials free of charge.</p>
							<p>b. Content Subjectivity. Content tends to elicit varying reactions among different people. You may come across Content that you find offensive, indecent, explicit or objectionable. Also, Content types, genres, categories, and descriptions are provided as suggestions to help with navigation, and Discovered does not guarantee that you will agree with them. You acknowledge these risks.</p>
							<p>c. Content Quality. Discovered uses various technologies to provide you with an optimal viewing experience. That said, quality of Content, including resolution, may be affected by the format of the Content, your location, the speed and bandwidth of your internet service, and the devices used, among other factors. HD and 4K Ultra HD availability for certain Content depends on your internet service and device capabilities. The time it takes you to begin playing Content will vary based on a number of factors, including your location, internet bandwidth, the number of devices simultaneously connecting to the same network, the Content you have selected, and the configuration of the device you are using. As a result, Discovered is unable to make any warranties about the Content in these respects.</p>
							<p>d. Content Presentation. We want you to have the best experience with our Services, including the ability to easily discover new Content. To help do that, Content you view across all Services may include promotional videos (e.g., previews or trailers) before and after that Content.</p>
							<p>e. Temporary Downloads. We know that you may not always have an internet connection when you want to watch your favorite Content. Discovered may give you the option to temporarily download certain Content on certain Compatible Devices so that you can watch it while you are offline ("Temporary Downloads"). Of course, there are some limitations, including: (i) the maximum number of devices that can store Temporary Downloads; (ii) the maximum number of Temporary Downloads that can be stored across Compatible Devices at any given time; (iii) how long Temporary Downloads will remain available to you; and (iv) geographic and device restrictions on playback.</p>
							
							<p>3.6 The Video Player. You may not modify, enhance, remove, interfere with, or otherwise alter in any way any portion of the Video Player, its underlying technology, any digital rights management mechanism, device, or other content protection or access control measure incorporated into the Video Player. This restriction includes, without limitation, disabling, reverse engineering, modifying, interfering with or otherwise circumventing the Video Player in any manner that enables users to view the Content without: (i) displaying visibly both the Video Player and all surrounding elements (including the graphical user interface, any advertising, copyright notices, and trademarks) of the Access Point where the Video Player is located; and (ii) having full access to all functionality of the Video Player, including, without limitation, all video quality and display functionality and all interactive, elective, or click-through advertising functionality.</p>
							<p>3.7 Embedding a Video Using the Video Player. Where Discovered has incorporated an embed option in connection with Content on the Services, you may embed videos using the Video Player, provided you do not embed the Video Player on any website or other location that (i) contains or hosts content that is unlawful, infringing, pornographic, obscene, defamatory, libelous, threatening, harassing, vulgar, indecent, profane, hateful, racially or ethnically offensive, encourages criminal conduct, gives rise to civil liability, violates any law, rule, or regulation, infringes any right of any third party including intellectual property rights, or is otherwise inappropriate or objectionable to Discovered (in Discovered's sole discretion), or (ii) links to infringing or unauthorized content (collectively, "Unsuitable Material"). You may not embed the Video Player into any hardware or software application, even for non-commercial purposes. Discovered reserves the right to prevent embedding to any website or other location that Discovered finds inappropriate or objectionable (as determined by Discovered in its sole discretion).</p>
							<p>3.8 Compatible Devices. In order to access the Services, you will need to use a computer, mobile device, streaming media player, or other device that meets the system and compatibility requirements that we establish from time to time (each, a “Compatible Device”). Please note that Compatible Devices may vary by Service. For example, certain devices may not be capable of streaming content but may be capable of streaming other Content. Features and functionalities that we make available through the Services may also differ by Compatible Device and the terms of your subscription. Please visit our Help Center at <a href="https://discovered.tv" class="policies_link" target="_blank">Discovered.tv/help</a> for a current list of Compatible Devices.</p>
							<p>3.9 Simultaneous Streams. The number of simultaneous streams of Content that you can access varies by Service and may require device and account verification</p>
							<p>3.10 Internet Service and Data Usage. In order to access the Services, you must have a high-speed broadband, wireless or similar internet connection from an internet service provider that meets certain technical specifications. Please note that multiple simultaneous streams, as well as HD and 4K Ultra HD Content, may require higher internet bandwidth. You are responsible for any costs associated with your internet service used to access the Services. Your use of the Services may count toward your data usage, depending on the terms of your agreement with your internet service provider.</p>
							<p>3.11 Ownership. You agree that you own and retain all rights to the content that you upload, and that you are providing a royalty-free license to Discovered TV, in exchange for any media exposure, digital media value and/or the revenue received by you. You further agree that the content you access and view as part of the services is owned or controlled by Discovered and Discovered's content programmers. The Services and the Content are protected by copyright, trademark, and other intellectual property laws.</p>
							<p>3.12 Your Responsibilities. In order for us to keep the Services safe and available for everyone to use, we all have to follow the same rules of the road. You and other users must use the Services for lawful, non-commercial, and appropriate purposes only. Your commitment to this principle is critical. You agree to observe the Services, Content, Video Player and embedding restrictions detailed above, and further agree that you will not use the Services in a way that:</p>
								<ul class="policies_datalist content_list">
									<li>violates the rights of others, including patent, trademark, trade secret, copyright, privacy, publicity, or other proprietary rights;</li>
									<li>uses technology or other means to access, index, frame or link to the Services (including the Content) that is not authorized by Discovered (including by removing, disabling, bypassing, or circumventing any content protection or access control mechanisms intended to prevent the unauthorized download, stream capture, linking, framing, reproduction, access to, or distribution of the Services);</li>
									<li>involves accessing the Services (including the Content) through any automated means, including "robots," "spiders," or "offline readers" (other than by individually performed searches on publicly accessible search engines for the sole purpose of, and solely to the extent necessary for, creating publicly available search indices - but not caches or archives - of the Services and excluding those search engines or indices that host, promote, or link primarily to infringing or unauthorized content);</li>
									<li>introduces viruses or any other computer code, files, or programs that interrupt, destroy, or limit the functionality of any computer software or hardware or telecommunications equipment;</li>
									<li>damages, disables, overburdens, impairs, or gains unauthorized access to the Services, including Discovered's servers, computer network, or user accounts.</li>
									<li>removes, modifies, disables, blocks, obscures or otherwise impairs any advertising in connection with the Services (including the Content);</li>
									<li>uses the Services to advertise or promote services that are not expressly approved in advance in writing by Discovered;</li>
									<li>collects information in violation of Discovered's Privacy Policy;</li>
									<li>encourages conduct that would constitute a criminal offense or give rise to civil liability;</li>
									<li>violates these Terms or any guidelines or policies posted by Discovered;</li>
									<li>interferes with any other party's use and enjoyment of the Services; or</li>
									<li>attempts to do any of the foregoing.</li>
								</ul>
							<p>If Discovered determines in its sole discretion that you are violating any of these Terms, we may (i) notify you, and (ii) use technical measures to block or restrict your access or use of the Services. In either case, you agree to immediately stop accessing or using in any way (or attempting to access or use) the Services, and you agree not to circumvent, avoid, or bypass such restrictions, or otherwise restore or attempt to restore such access or use.</p>
							<p>3.13 No Spam/Unsolicited Communications. We know how annoying and upsetting it can be to receive unwanted email or instant messages from people you do not know. Therefore, you may not use the Services to harvest information about users for the purpose of sending, or to facilitate or encourage the sending of, unsolicited bulk or other communications. You understand that we may employ technical measures to prevent spam or unsolicited bulk or other communications from entering, utilizing, or remaining within our computer or communications networks. If you Post (as defined below in Section 7) or otherwise send spam, advertising, or other unsolicited communications of any kind through the Services, you acknowledge that you will have caused substantial irreparable harm to Discovered and that the amount of such harm would be extremely difficult to measure.</p>
							<p>3.14 Software Downloads. In order to participate in certain Services or access certain Content, you may be notified that it is necessary to download software or other materials or agree to additional terms and conditions. Unless otherwise provided by these additional terms and conditions, they are hereby incorporated into these Terms.</p>
							<p>3.15 Modification/Suspension/Discontinuation. We regularly make changes to the Services. The availability of the Content, as well as Access Points and Compatible Devices through which the Services are available, will change from time to time. Discovered reserves the right to replace or remove any Content and Access Points available to you through the Services, including specific titles and networks/channels, and to otherwise make changes in how we operate the Services. Additionally, you agree that for various reasons, such as restrictions from content programmers and other limitations or considerations from third parties, certain Content and functionality that may be available through one Access Point or Compatible Device may not be available through another Access Point or Compatible Device. We hope not to, but we may change, suspend, or discontinue - temporarily or permanently - some or all of the Services (including the Content and the Compatible Devices through which the Services are accessed), with respect to any or all users, at any time without notice. In our continued assessment of the Services, we may from time to time, with respect to any or all of our users, experiment with or otherwise offer certain features or other elements of the Services, including promotional features, user interfaces, plans, pricing, and advertisements. You acknowledge that Discovered may do so in Discovered's sole discretion at any time without notice. You also agree that Discovered will not be liable to you for any modification, suspension, or discontinuance of the Services, although if you are a Discovered subscriber and Discovered suspends or discontinues your subscription to the Services, Discovered may, in its sole discretion, provide you with a credit, refund, discount or other form of consideration (for example, we may credit additional days of service to your account) in accordance with Section 4 below. However, if Discovered terminates your account or suspends or discontinues your access to Services due to your violation of these Terms, then you will not be eligible for any such credit, refund, discount or other consideration.</p>
							<p>3.16 Customer Service. If we can be of help to you, please do not hesitate to contact our customer service department by visiting our Help Center at <a href="https://discovered.tv" class="policies_link" target="_blank">Discovered.tv/help</a>. It would be our pleasure to serve you. We aim to deliver first-class customer service, but in the unlikely event that a customer service representative or material posted to our Help Center provides information that is inconsistent with these Terms, please be aware that these Terms will control.</p>
							
							<h4 class="policies_heading" id="04">04. CONTENT CREATORS AND PAYMENTS</h4>
							<p>4.1 Earnings: Your earnings from Discovered will be aggregated across your content portfolio and paid on a bi-weekly basis. From the date you upload your first video, you will receive money through payment method of your choice, following your completion of an IRS Form W-9 and after an initial cooling period of 67 days. </p>
							
							<h4 class="policies_heading" id="05">05. ACCOUNTS AND REGISTRATION</h4>
							<p>You are responsible for all use of your account, including use of your account by other members of your household. By allowing others to access your account or to create profiles within your account, you agree to be responsible for ensuring that they comply with these Terms and you agree to be responsible for their activity using the Services.</p>
							<p>All registration information you submit must be accurate and updated. Please keep your password confidential. You will not have to reveal it to any Discovered representative. Because you are responsible for all use of your account, including unauthorized use by any third party, please be very careful to guard the security of your password. Please notify us by email using the customer support form from our Help Center at <a href="https://discovered.tv" class="policies_link" target="_blank">Discovered.tv/help</a> if you suspect any unauthorized use of your account. Please also make sure to notify us if your registration information changes, in case we need to contact you.</p>
							<p>You may find information on how to delete your Discovered account by logging in on the Discovered Site and viewing your account details. Please identify your account and provide a valid reply email address in the event we require additional information to terminate your account. Please note, if you are a subscriber you must first cancel your subscription before you will be able to delete your account. Please see the section "Ongoing Subscription and Cancellation" above for instructions on how to cancel your subscription.</p>
							<p>We reserve the right to immediately terminate or restrict your account or your use of the Services or access to Content at any time, without notice or liability, if Discovered determines in its sole discretion that you have breached these Terms, violated any law, rule, or regulation, engaged in other inappropriate conduct, or for any other business reason. We also reserve the right to terminate your account or your use of the Services or access to Content if such use places an undue burden on our networks or servers. Of course, we would prefer to avoid such termination; therefore, we may use technology to limit activities, such as the number of calls to the Discovered servers being made or the volume of User Material (as defined below in Section 7) being Posted, and you agree to respect these limitations and not take any steps to circumvent, avoid, or bypass them.</p>
							
							<h4 class="policies_heading" id="06">06. COLLECTION AND USE OF PERSONAL INFORMATION</h4>
							<p>For information about Discovered's policies and practices regarding the collection and use of your information, please read Discovered's Privacy Policy available at Discovered.tv/privacy. The Privacy Policy is incorporated by reference and made part of these Terms. Thus, by agreeing to these Terms, you agree that your presence on the Discovered Site and use of the Services through any other Access Point or Compatible Device are governed by the Discovered Privacy Policy in effect at the time of your use.</p>
							
							<h4 class="policies_heading" id="07">07. USER REVIEWS, COMMENTS, AND OTHER MATERIAL</h4>
							<p>7.1 Your Posts. As part of the Services, users may have an opportunity to publish, transmit, submit, or otherwise post (collectively, "Post") reviews, comments, or other materials (collectively, "User Material"). In order to keep the Services enjoyable for all of our users, you must adhere to the rules below, as well as additional rules applicable to any Discovered-hosted site.</p>
							<p>Please choose carefully the User Material that you Post. Please limit yourself to User Material directly relevant to the Services. Moreover, you must not Post User Material that: (i) contains Unsuitable Material (as defined above in Section 3); or (ii) improperly claims the identity of another person. Please note that if you Post User Material on Discovered using a third party service, such as a social network or email provider, your first and last name or other user ID may appear to the public each time you Post. We advise that you do not, and you should also be careful if you decide to, Post additional personal information, such as your email address, telephone number, or street address.</p>
							<p>You must be, or have first obtained permission from, the rightful owner of any User Material you Post. By submitting User Material, you represent and warrant that you own the User Material or otherwise have the right to grant Discovered the license provided below. You also represent and warrant that the Posting of your User Material does not violate any right of any party, including privacy rights, publicity rights, and intellectual property rights. In addition, you agree to pay for all royalties, fees, and other payments owed to any party by reason of your Posting User Material. Discovered will remove all User Material if we are properly notified that such User Material infringes on another person's rights. You acknowledge that Discovered does not guarantee any confidentiality with respect to any User Material.</p>
							<p>By Posting User Material, you are not forfeiting any ownership rights in such material to Discovered. After Posting your User Material, you continue to retain all of the same ownership rights you had prior to Posting. By Posting your User Material, you grant Discovered a limited license to use, display, reproduce, distribute, modify, delete from, add to, prepare derivative works of, publicly perform, and publish such User Material through the Services and on other platforms and services worldwide, including on or through any Access Point, in perpetuity, in any media formats and any media channels now known or hereinafter created. The license you grant to Discovered is non-exclusive (meaning you are not prohibited by us from licensing your User Material to anyone else in addition to Discovered), fully-paid, royalty-free (meaning that Discovered is not required to pay you for the use of your User Material), and sublicensable (so that Discovered is able to use its affiliates, subcontractors, and other partners, such as internet content delivery networks, to provide the Services). By Posting your User Material, you also hereby grant each user of the Services a non-exclusive, limited license to access your User Material, and to use, display, reproduce, distribute, and perform such User Material as permitted through the functionality of the Services and under these Terms.</p>
							<p>7.2 Third Party Posts. Despite these restrictions, please be aware that some material provided by users may be objectionable, unlawful, inaccurate, or inappropriate. Discovered does not endorse any User Material, and User Material that is Posted does not reflect the opinions or policies of Discovered. We reserve the right, but have no obligation, to monitor User Material and to restrict or remove User Material that we determine, in our sole discretion, is inappropriate or for any other business reason, as permitted by law. In no event does Discovered assume any responsibility or liability whatsoever for any User Material, and you agree to waive any legal or equitable rights or remedies you may have against Discovered with respect to such User Material. You can help us tremendously by notifying us of any inappropriate User Material you find by emailing <a href="mailto:help@Discovered.tv?subject=Inappropriate User Material" class="policies_link" target="_blank">help@Discovered.tv</a> (subject line: "Inappropriate User Material").</p>
							
							<h4 class="policies_heading " id="08">08. AD EXPLOITATION</h4>
							<p>You irrevocably authorize Discovered to insert advertisement within your uploaded content, at its sole discretion and you reserve no rights whatsoever, regarding the context of the advertisement insert, including but not limited to, the irrevocable waiver of any and all rights, droit moral rights, or otherwise.</p>
							
							<h4 class="policies_heading" id="09">09. LINKED DESTINATIONS AND ADVERTISING</h4>
							<p>9.1 Third Party Destinations. If we provide links or pointers to other websites or destinations, you should not infer or assume that Discovered operates, controls, or is otherwise connected with these other websites or destinations. When you click on a link within the Services, we will not warn you that you have left the Services and are subject to the terms and conditions (including privacy policies) of another website or destination. In some cases, it may be less obvious than others that you have left the Services and reached another website or destination. Please be careful to read the terms of use and privacy policy of any other website or destination before you provide any information or engage in any transactions. These Terms do not govern your use of another website or destination.</p>
							<p>Discovered is not responsible for the content or practices of any website or destination other than the Discovered Site, even if it links to the Discovered Site and even if the website or destination is operated by a company affiliated or otherwise connected with Discovered. By using the Services, you acknowledge and agree that Discovered is not responsible or liable to you for any content or other materials hosted and served from any website or destination other than the Discovered Site.</p>
							<p>9.2 Third Party Advertisements and Services. Discovered takes no responsibility for and does not endorse any third party advertisements or any third party material Posted on any Access Point where the Services are available, nor do we take any responsibility for the products or services provided by advertisers. Any dealings you have with advertisers while using the Services, including through engaging with interactive advertisements, are between you and the advertiser, and you agree that Discovered is not liable for any loss or claim that you may have against an advertiser. If you provide any confidential or personal information or engage in any transaction through an advertisement, Discovered is not responsible for such information or transaction and we encourage you to read the terms of use and privacy policy of the advertiser or other party collecting such information or engaging in such transaction.</p>
							
							<h4 class="policies_heading" id="10">10. TRADEMARKS</h4>
							<p>Discovered, Discovered USA, Discovered.tv, dTv, the Discovered logo, and other Discovered marks, graphics, logos, scripts, and sounds are trademarks of Discovered. None of the Discovered trademarks may be copied, downloaded, or otherwise exploited.</p>
							
							<h4 class="policies_heading" id="11">11. UNSOLICITED SUBMISSIONS</h4>
							<p>It is Discovered's policy not to accept unsolicited submissions, including scripts, story lines, articles, fan fiction, characters, drawings, information, suggestions, ideas, or concepts. Discovered's policy is to delete any such submission without reading it. Therefore, any similarity between an unsolicited submission and any elements in any Discovered creative work, including a film, series, story, title, or concept, would be purely coincidental.</p>
							
							<h4 class="policies_heading" id="12">12. DISCLAIMER OF WARRANTIES, LIMITATION OF LIABILITY AND INDEMNITY</h4>
							<p>WHILE WE DO OUR BEST TO PROVIDE THE OPTIMAL PERFORMANCE OF THE SERVICES, YOU AGREE THAT USE OF THE SERVICES IS AT YOUR OWN RISK. THE SERVICES, INCLUDING THE DISCOVERED SITE, THE CONTENT, THE VIDEO PLAYER, THE FEATURES, USER MATERIAL, AND ANY OTHER MATERIALS CONTAINED ON OR PROVIDED THROUGH ANY ACCESS POINT OR COMPATIBLE DEVICE, ARE PROVIDED "AS IS" AND, TO THE FULLEST EXTENT PERMITTED BY LAW, ARE PROVIDED WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED. WITHOUT LIMITING THE FOREGOING, DISCOVERED DOES NOT MAKE ANY WARRANTIES OF FITNESS FOR A PARTICULAR PURPOSE, TITLE, MERCHANTABILITY, COMPLETENESS, AVAILABILITY, SECURITY, COMPATIBILITY OR NONINFRINGEMENT; OR THAT THE SERVICES WILL BE UNINTERRUPTED, FREE OF VIRUSES AND OTHER HARMFUL COMPONENTS, ACCURATE, ERROR FREE, OR RELIABLE.</p>
							<p>IN NO EVENT SHALL DISCOVERED OR ITS AFFILIATES, SUCCESSORS, AND ASSIGNS, AND EACH OF THEIR RESPECTIVE INVESTORS, DIRECTORS, OFFICERS, EMPLOYEES, AGENTS, AND SUPPLIERS (INCLUDING DISTRIBUTORS AND CONTENT PROGRAMMERS) (COLLECTIVELY, THE "DISCOVERED PARTIES"), BE LIABLE FOR ANY DIRECT, INDIRECT, PUNITIVE, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR OTHER DAMAGES, INCLUDING LOSS OF PROFITS, ARISING OUT OF OR IN ANY WAY RELATED TO THE USE OF THE SERVICES (INCLUDING ANY INFORMATION, PRODUCTS, OR SERVICES ADVERTISED IN, OBTAINED ON, OR PROVIDED THROUGH ANY ACCESS POINT OR COMPATIBLE DEVICE), WHETHER BASED IN CONTRACT, TORT, STRICT LIABILITY, OR OTHER THEORY, EVEN IF THE DISCOVERED PARTIES HAVE BEEN ADVISED OF THE POSSIBILITY OF DAMAGES. CERTAIN STATE LAWS DO NOT ALLOW LIMITATIONS ON IMPLIED WARRANTIES OR THE EXCLUSION OR LIMITATION OF CERTAIN DAMAGES. IF THESE LAWS APPLY TO YOU, SOME OR ALL OF THE ABOVE DISCLAIMERS, EXCLUSIONS, OR LIMITATIONS MAY NOT APPLY TO YOU. NOTHING IN THESE TERMS SHALL AFFECT ANY NON-WAIVABLE STATUTORY RIGHTS THAT APPLY TO YOU. IN NO EVENT SHALL OUR TOTAL LIABILITY TO YOU FOR ALL DAMAGES, LOSSES AND CAUSES OF ACTION WHETHER IN CONTRACT, TORT (INCLUDING NEGLIGENCE) OR OTHERWISE EXCEED THE AMOUNT PAID BY YOU TO US, IF ANY, FOR ACCESSING OR PARTICIPATING IN ANY ACTIVITY RELATED TO USE OF THE SERVICES OR $50 (WHICHEVER IS LESS).</p>
							<p>YOU AGREE TO DEFEND, INDEMNIFY, AND HOLD HARMLESS THE DISCOVERED PARTIES FROM AND AGAINST ANY AND ALL LIABILITIES, CLAIMS, DAMAGES, EXPENSES (INCLUDING REASONABLE ATTORNEYS' FEES AND COSTS), AND OTHER LOSSES ARISING OUT OF OR IN ANY WAY RELATED TO YOUR BREACH OR ALLEGED BREACH OF THESE TERMS OR YOUR USE OF THE SERVICES (INCLUDING YOUR USE OF THE CONTENT). DISCOVERED RESERVES THE RIGHT, AT OUR OWN EXPENSE, TO EMPLOY SEPARATE COUNSEL AND ASSUME THE EXCLUSIVE DEFENSE AND CONTROL OF ANY MATTER OTHERWISE SUBJECT TO INDEMNIFICATION BY YOU.</p>
							<p><strong>IN THE EVENT OF ANY DISPUTE WITH DISCOVERED IN CONNECTION WITH THIS AGREEMENT, YOU WARRANT AND REPRESENT YOU WILL SEEK REMEDIES AGAINST DISCOVERED ONLY, AND YOU WILL NOT BRING OR COMMENCE ANY ACTION WHATSOEVER AGAINST ANY OFFICER, DIRECTOR, AGENT, REPRESENTATIVE, OR MEMBER OF DISCOVERED IN AN INDIVIDUAL CAPACITY.  IF ANY COURT OR ARBITRATOR OF COMPETENT JURISDICTION SHALL AGREE TO HEAR A DISPUTE ACTION BROUGHT BY YOU AGAINST ANY OFFICER, DIRECTOR, AGENT, REPRESENTATIVE OR MEMBER OF DISCOVERED IN AN INDIVIDUAL CAPACITY, THEN THE AFOREMENTIONED OFFICER, DIRECTOR, AGENT, REPRESENTATIVE OR MEMBER OF DISCOVERED AGAINST WHOM SUCH AN ACTION HAS BEEN COMMENCED MAY USE THIS PARAGRAPH AS A FULL AND COMPLETE DEFENSE TO ANY SUCH ACTION, AND YOU SHALL BE LIABLE FOR ANY COSTS AND ATTORNEYS’ FEES INCURRED BY THE OFFICER, DIRECTOR, AGENT, REPRESENTATIVE OR MEMBER DEFENDING SUCH ACTION.</strong></p>
							
							
							<h4 class="policies_heading" id="13">13. NOTICE AND PROCEDURE FOR CLAIMS OF COPYRIGHT INFRINGEMENT</h4>
							<p>If you believe that any Content, User Material, or other material provided through the Services, including through a link, infringes your copyright, you should notify Discovered of your infringement claim in accordance with the procedure set forth below.</p>
							<p>We will process each notice of alleged infringement that Discovered receives and take appropriate action in accordance with applicable intellectual property laws. A notification of claimed copyright infringement should be emailed to Discovered's copyright agent at <a href="mailto:help@Discovered.tv?subject=DMCA Takedown Request" class="policies_link" target="_blank">help@Discovered.tv</a> (subject line: "DMCA Takedown Request"). You may also contact us by mail at:</p>
							<address class="policies_address">
							Attention:</br> 
							Discovered USA, Inc.</br>  
							PO Box: 67369</br> 
							Scotts Valley, CA 95067
							</address>
							<p>To be effective, the notification must be in writing and contain the following information: (i) an electronic or physical signature of the person authorized to act on behalf of the owner of an exclusive copyright interest; (ii) a description of the copyrighted work that you claim has been infringed; (iii) a description of where the material that you claim is infringing is located on the Services that is reasonably sufficient to enable Discovered to identify and locate the material; (iv) how Discovered can contact you, such as your address, telephone number, and email address; (v) a statement by you that you have a good faith belief that the disputed use is not authorized by the copyright owner, its agent, or the law; and (vi) a statement by you that the above information in your notice is accurate and under penalty of perjury that you are authorized to act on behalf of the copyright owner or the owner of an exclusive right in the material. Emails sent to <a href="mailto:help@Discovered.tv" class="policies_link" target="_blank">help@Discovered.tv</a> for purposes other than communication about copyright infringement may not be answered.</p>
							<p>Discovered has a policy of terminating repeat infringers in appropriate circumstances.</p>
							
							<h4 class="policies_heading" id="14">14. ARBITRATION OF CLAIMS</h4>
							<p>PLEASE READ THIS CAREFULLY. WE WANT YOU TO KNOW HOW IT AFFECTS YOUR RIGHTS. If you have an issue with the Services, we encourage you to review our frequently asked questions or contact our customer service team through our Help Center at Discovered.tv/help. In the event there is an issue that still requires attention, we want to make the resolution process as quick and efficient as possible. We also want to specify now what each of us should expect in order to avoid any confusion later. To that end, you and Discovered agree to first discuss any issue informally for at least 30 days. To do that, please send your full name and contact information, your concern and your proposed solution by mail to us at: </p>
								<address class="policies_address">
								Discovered USA, Inc.</br>
								Attn: Legal Department.</br>
								PO Box: 67369</br>
								Scotts Valley, CA 95067
								</address>
							<p>If we would like to discuss an issue with you, we will contact you using the email address you provided when you registered for Discovered.</p>
							<p>If we do not reach an agreed upon solution after our discussions for at least 30 days, you and Discovered agree that any and all claims that either of us may have arising out of or relating to: (i) these Terms (including formation, performance, or breach of them, and including the scope and enforceability of this arbitration provision); (ii) the Privacy Policy, which is incorporated in these Terms; (iii) any aspect of our relationship with each other; and (iv) use of the Services, must be resolved through binding arbitration before the American Arbitration Association (“AAA”) using its Consumer Arbitration Rules, available at <a href="www.adr.org" class="policies_link" target="_blank">www.adr.org</a> or by calling the AAA at 1-800-778-7879. As an exception to this arbitration agreement, Discovered is happy to give you the right to pursue in small claims court any claim that is within that court's jurisdiction as long as you proceed only on an individual basis.</p>
							
							<p>You and Discovered agree to arbitrate in each of our individual/corporate capacities only, not as a representative or member of a class, and each of us expressly waives any right to file a class action or seek relief on a class basis.
							</br>
							Rather than force everyone to visit us in California, if you can demonstrate that arbitration in California would create an undue burden to you, you are free to initiate the arbitration in your home state. Otherwise, the arbitration hearings will be held in Santa Cruz County, California.  If you are a citizen of any European Union country or Switzerland, Norway or Iceland, the governing law and forum shall be the laws and courts of your usual place of residence.
							</br></br>
							You may download or copy a form Notice and a form to initiate arbitration at www.adr.org. If you initiate the arbitration, Discovered will reimburse you for your filing fee, unless your claim is for greater than $10,000, in which event you are responsible for paying the filing fee. Regardless of who initiates the arbitration, Discovered will pay any other arbitration fees, including your share of arbitrator compensation.
							</br></br>
							It is important that you understand that the arbitrator's decision will be binding and may be entered as a judgment in any court of competent jurisdiction. If the arbitrator rules against Discovered, in addition to accepting whatever responsibility is ordered by the arbitrator, we think it's fair that Discovered reimburse your reasonable attorneys' fees and costs, regardless of who initiated the arbitration. In addition, if the arbitrator rules in Discovered's favor, Discovered will not seek reimbursement of our attorney's fees and costs, regardless of who initiated the arbitration. For clarity, this arbitration provision will survive cancellation of your Discovered account.
							</br></br>
							If you're not sure what all of this means, of course please feel free to ask an attorney.
							</br></br>
							Specifying what happens if an issue arises with one of our users is never a fun topic. But we pride ourselves on transparency and we thank you in advance for understanding why it's important that you and Discovered agree on the process described in this Section.
							</p>
							
							<h4 class="policies_heading  page_scroll" data-scroll="15">15. LIMITATION ON TIME TO BRING A CLAIM</h4>
							<p>To help resolve any issues between us promptly, you and Discovered agree to bring any claim arising out of or relating to these Terms (including Discovered’s Privacy Policy), our relationship, or the use of the Services within one year after a claim arises; otherwise, the claim is waived. This limitation applies regardless of the venue in which such claim is or could otherwise be asserted.</p>
							
							<h4 class="policies_heading" id="16">16. GENERAL INFORMATION</h4>
							<p>16.1 International Use. We are a company based in the United States and offer our Services to users in the United States. Discovered's goal is to bring you as much Content as is legally available. That said, we are limited by the rights that our content programmers grant to us. Access to the Services from locations where Discovered does not have rights, that are not permitted by the terms of your subscription, or where Discovered does not make the Services available is prohibited.
							</br></br>
							16.2 Export Controls. Software and the transmission of applicable technical data, if any, in connection with the Services are subject to export controls. You agree to comply with all applicable laws regarding software and the transmission of technical data exported from the United States or the country in which you reside.
							</br></br>
							16.3 Choice of Law and Forum. These Terms are governed by, and construed in accordance with, the laws of the State of California without giving effect to principles of conflicts of law. To the extent that the arbitration provision outlined in Section 14 is not applicable (e.g., when confirming an arbitration award), you and Discovered agree to submit to the exclusive jurisdiction of the courts located in the Santa Cruz County of the State of California.
							</br></br>
							16.4 No Waiver/Reliance. If you see other parties violating these Terms, we would appreciate it if you would let us know at <a href="mailto:help@Discovered.tv?subject=TOU Violation" class="policies_link" target="_blank">help@Discovered.tv</a> (subject line: "TOU Violation"). Precisely how Discovered responds to a party that is violating these Terms will be determined after carefully analyzing all of the facts and circumstances of a particular case. You may not rely upon Discovered's precise response with respect to one party or one situation as any indication of what Discovered might do with respect to another party or another situation, even if the parties or situations appear to you to be similar. Similarly, if we fail to act in response to a violation of these Terms, you should not assume that we do not object to the violation or even that we are aware of it. In addition, you may not construe a waiver of any provision of these Terms with respect to any party as a waiver of that provision (or any other provision) with respect to either that party or any other party. Further, Discovered's decision to delay exercising or enforcing any right or remedy under these Terms shall not constitute a waiver of such right or remedy. Even if Discovered acts in a way that appears to you to be inconsistent with these Terms, Discovered's action shall not be deemed a waiver or constructive amendment of these Terms.
							</br></br>
							16.5 Integration, Amendment, Severability, and Electronic Communications. Please note that these Terms, including Discovered's Privacy Policy which is incorporated in these Terms and any end user license agreement that might accompany the applicable Service, constitute the entire legal agreement between you and Discovered and govern your use of the Services (including your use of the Content) (but excludes any services, if any, that Discovered may provide to you under a separate signed written agreement), and completely replaces any prior agreements between you and Discovered in relation to the Services. These Terms operate to the fullest extent permissible by law. If any provision of these Terms is held to be unlawful, void, or unenforceable, you and we agree that the provision will be deemed severable from these Terms and will not affect the validity and enforceability of any remaining provisions.
							</br></br>
							From time to time, we may communicate with you about the Services and these Terms electronically (e.g., emails to your registered email address, notices on the Discovered Site and other Access Points). You consent to receive electronic communications from Discovered and further agree that any notices, agreements, disclosures, and other communications that we send to you electronically will satisfy any applicable legal notification requirements. We recommend that you keep a copy of any electronic communications we send to you for your records.
							</br></br>
							Thank you for taking the time to read these Terms. By understanding and agreeing to follow these Terms, the experience will be better for all users. It is our goal to provide you with a first class user experience, so if you have any questions or comments about these Terms, please contact us at: <a href="mailto:help@Discovered.tv" class="policies_link" target="_blank">help@Discovered.tv.</a> Enjoy the Services!

							</p>
							
						</div>
					</div>
				</div>
		</div>
			</div>
		</div>
	</div>
</div>