<?php

	require APPPATH . 'third_party/twilio-php-main/src/Twilio/autoload.php';
	
	use Twilio\Rest\Client;

	function twillio_msg(){
		// Require the bundled autoload file - the path may need to change
		// based on where you downloaded and unzipped the SDK
		// Your Account SID and Auth Token from twilio.com/console
		$sid = 'AC241754eb5271e5d938fd3e2444592d1f';
		$token = 'f8cf1c5927efd8898fa7a23aa85b9b3e';
		$client = new Client($sid, $token);
		try{
		// Use the client to do fun stuff like send text messages!
		$client->messages->create(
			// the number you'd like to send the message to
			'+919827868313',
			[
				// A Twilio phone number you purchased at twilio.com/console
				'from' => '+14105143520',
				// the body of the text message you'd like to send
				'body' => "Hey Jenny! Good luck on the bar exam!"
			]
		);
		
		}catch(Twilio\Exceptions\RestException $e){
			echo '<pre>';
			print_r($e);
		}
	}
	
	/* function nexmo_msg(){
		require APPPATH . 'third_party/nexmo/vendor/autoload.php';
		$basic  = new \Nexmo\Client\Credentials\Basic('6b69a567', 'SnBxUjVhQrsA83H1');
		$client = new \Nexmo\Client($basic);

		$message = $client->message()->send([
			'to' => '919827868313',
			'from' => '09827868313',
			'text' => 'Hello from Vonage SMS API'
		]);
	} */
	function nexmo_msg(){
		// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
		$ch = curl_init();

		curl_setopt($ch, CURLOPT_URL, 'https://rest.nexmo.com/sms/json');
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
		curl_setopt($ch, CURLOPT_POST, 1);
		curl_setopt($ch, CURLOPT_POSTFIELDS, "from=09827868313&text=Hello from Vonage SMS API&to=919827868313&api_key=6b69a567&api_secret=SnBxUjVhQrsA83H1");

		$headers = array();
		$headers[] = 'Content-Type: application/x-www-form-urlencoded';
		curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

		$result = curl_exec($ch);
		if (curl_errno($ch)) {
			echo 'Error:' . curl_error($ch);
		}
		curl_close($ch);
		echo  '<pre>';
		print_r($result);
	}